// SPDX-License-Identifier: Zlib
package scripts;

import haxe.Json;
import haxe.ds.StringMap;
import haxe.io.Path;
import sys.io.File;

using StringTools;

typedef LicenseSchema = {
    reference: String,
    isDeprecatedLicenseId: Bool,
    detailsUrl: String,
    referenceNumber: Int,
    name: String,
    licenseId: String,
    seeAlso: Array<String>,
    isOsiApproved: Bool,
    isFsfLibre: Null<Bool>,
    ?mangledIdentifier: String,
};

typedef LicenseDataSchema = {
    licenses: Array<LicenseSchema>,
    licenseListVersion: String,
    releaseDate: String,
}

function mangleName(name: String): String {

    var name = name.replace("-", "")
        .replace("–", "")
        .replace(".", "_")
        .replace(",", "")
        .replace("'", "")
        .replace(":", "")
        .replace("+", " Plus ")
        .replace("/", "")
        .replace("(", " ")
        .replace(")", " ")
        .replace("!", "")
        .replace("*", "")
        .replace("é", "e")
        .replace("&", "and")
        .replace("\"", " ");

    if (name.endsWith("License")) {
        name = name.substr(0, name.length - "License".length);
    }

    final nameBuf = new StringBuf();
    for (part in name.trim().split(" ")) {
        if (part.length >= 1) {
            nameBuf.add("_");
            nameBuf.add(part.toUpperCase());
        }
    }

    var name = nameBuf.toString();
    if (name.charCodeAt(1) < "0".code || name.charCodeAt(1) > "9".code) {
        name = name.substr(1);
    }

    return name;
}

final class GenerateLicenses {

    private static function main(): Void {

        trace("Reading data...");
        final dataJson = File.getContent(Path.join([Sys.getCwd(), "data", "licenses.json"]));
        trace("Parsing data...");
        final data: LicenseDataSchema = Json.parse(dataJson);
        final licensesByName = new StringMap<LicenseSchema>();

        trace("Generating source...");
        final source = new StringBuf();
        source.add("// Auto generated by script. DO NOT EDIT.\n");
        source.add("package spdx;\n");

        for (license in data.licenses) {

            source.add("\n");

            final existingLicense = licensesByName.get(license.name);
            if (existingLicense == null || existingLicense.isDeprecatedLicenseId == true) {
                licensesByName.set(license.name, license);
            }

            license.mangledIdentifier = mangleName(license.name);
            if (license.isDeprecatedLicenseId == true) {
                source.add("@:deprecated ");
                license.mangledIdentifier = license.mangledIdentifier + "_";
            }

            source.add("final ");
            source.add(license.mangledIdentifier);
            source.add(": spdx.License = new spdx.License(\n    /* name          */ \"");
            source.add(license.name.replace("\"", "\\\""));
            source.add("\",\n    /* id            */ \"");
            source.add(license.licenseId);
            source.add("\",\n    /* deprecated?   */ ");
            source.add(license.isDeprecatedLicenseId == true ? "true" : "false");
            source.add(",\n    /* OSI approved? */ ");
            source.add(license.isOsiApproved == true ? "true" : "false");
            source.add(",\n    /* FSF libre?    */ ");
            source.add(license.isFsfLibre == true ? "true" : "false");
            source.add("\n);\n");
        }

        source.add("\nfinal ALL_BY_ID: haxe.ds.StringMap<spdx.License> = [\n");
        for (license in data.licenses) {
            source.add("    \"");
            source.add(license.licenseId);
            source.add("\" => ");
            source.add(license.mangledIdentifier);
            source.add(",\n");
        }
        source.add("];\n");

        source.add("\nfinal ALL_BY_NAME: haxe.ds.StringMap<spdx.License> = [\n");
        for (name => license in licensesByName) {
            source.add("    \"");
            source.add(name.replace("\"", "\\\""));
            source.add("\" => ");
            source.add(license.mangledIdentifier);
            source.add(",\n");
        }
        source.add("];\n");

        source.add("\nfinal ALL: haxe.ds.ReadOnlyArray<spdx.License> = [\n");
        for (license in data.licenses) {
            source.add("    ");
            source.add(license.mangledIdentifier);
            source.add(",\n");
        }
        source.add("];\n");

        trace("Saving source...");
        final dst = Path.join([Sys.getCwd(), "src", "spdx", "Licenses.hx"]);
        File.saveContent(dst, source.toString());
    }
}
